# ============================================================================
# VANDA CHATBOT - Google Cloud Build Configuration
# ============================================================================
# Deploy automatico su Cloud Run quando push su branch master

steps:
  # STEP 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vanda-chatbot:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vanda-chatbot:latest'
      - '.'
    id: 'build-image'

  # STEP 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vanda-chatbot:$COMMIT_SHA'
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vanda-chatbot:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # STEP 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vanda-chatbot'
      - '--image=gcr.io/$PROJECT_ID/vanda-chatbot:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=60s'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--port=8080'
      # Environment variables
      - '--set-env-vars=ENV=production'
      - '--set-env-vars=LOG_LEVEL=INFO'
      - '--set-env-vars=SUPABASE_TABLE_NAME=documents'
      - '--set-env-vars=RAG_DEFAULT_MATCH_COUNT=3'
      - '--set-env-vars=RAG_DEFAULT_MATCH_THRESHOLD=0.60'
      - '--set-env-vars=RAG_MAX_CONTEXT_LENGTH=8000'
      - '--set-env-vars=RAG_ENABLE_METADATA_FILTERS=true'
      - '--set-env-vars=LLM_DEFAULT_MODEL=gpt-4o-mini'
      - '--set-env-vars=LLM_DEFAULT_TEMPERATURE=0.5'
      - '--set-env-vars=LLM_MAX_TOKENS=500'
      - '--set-env-vars=LLM_STREAM_ENABLED=true'
      # Secrets from Secret Manager
      - '--set-secrets=OPENAI_API_KEY=openai-key:latest'
      - '--set-secrets=SUPABASE_URL=supabase-url:latest'
      - '--set-secrets=SUPABASE_KEY=supabase-key:latest'
    id: 'deploy-cloud-run'
    waitFor: ['push-image-sha']

# Image stored in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/vanda-chatbot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/vanda-chatbot:latest'

# Build timeout (20 minutes max)
timeout: 1200s

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
