# ============================================================================
# VANDA ADMIN PANEL - Google Cloud Build Configuration
# ============================================================================
# Deploy automatico admin panel Streamlit su Cloud Run

steps:
  # STEP 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vanda-admin:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vanda-admin:latest'
      - '-f'
      - 'admin/Dockerfile'
      - '.'
    id: 'build-image'

  # STEP 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vanda-admin:$COMMIT_SHA'
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vanda-admin:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # STEP 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vanda-admin'
      - '--image=gcr.io/$PROJECT_ID/vanda-admin:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300s'
      - '--max-instances=3'
      - '--min-instances=0'
      - '--port=8501'
      # Secrets from Secret Manager
      - '--set-secrets=SUPABASE_URL=supabase-url:latest'
      - '--set-secrets=SUPABASE_KEY=supabase-key:latest'
    id: 'deploy-cloud-run'
    waitFor: ['push-image-sha']

# Image stored in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/vanda-admin:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/vanda-admin:latest'

# Build timeout (15 minutes max)
timeout: 900s

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
